export interface ILanguageData {
	id: number
	Language: string
	Name: string
}

export interface ILanguageData {
	id: number
	Language: string
	Name: string
	Flag: string
}

export const LanguageData: ILanguageData[] = [
	{ id: 1, Language: 'af', Name: 'Afrikaans', Flag: '🇿🇦' },
	{ id: 2, Language: 'sq', Name: 'Albanian', Flag: '🇦🇱' },
	{ id: 3, Language: 'am', Name: 'Amharic', Flag: '🇪🇹' },
	{ id: 4, Language: 'ar', Name: 'Arabic', Flag: '🇸🇦' },
	{ id: 5, Language: 'hy', Name: 'Armenian', Flag: '🇦🇲' },
	{ id: 6, Language: 'az', Name: 'Azerbaijani', Flag: '🇦🇿' },
	{ id: 7, Language: 'eu', Name: 'Basque', Flag: '🇪🇸' },
	{ id: 8, Language: 'be', Name: 'Belarusian', Flag: '🇧🇾' },
	{ id: 9, Language: 'bn', Name: 'Bengali', Flag: '🇧🇩' },
	{ id: 10, Language: 'bs', Name: 'Bosnian', Flag: '🇧🇦' },
	{ id: 11, Language: 'bg', Name: 'Bulgarian', Flag: '🇧🇬' },
	{ id: 12, Language: 'ca', Name: 'Catalan', Flag: '🇪🇸' },
	{ id: 13, Language: 'ceb', Name: 'Cebuano', Flag: '🇵🇭' },
	{ id: 14, Language: 'zh-CN', Name: 'Chinese (Simplified)', Flag: '🇨🇳' },
	{ id: 15, Language: 'zh-TW', Name: 'Chinese (Traditional)', Flag: '🇹🇼' },
	{ id: 16, Language: 'co', Name: 'Corsican', Flag: '🇫🇷' },
	{ id: 17, Language: 'hr', Name: 'Croatian', Flag: '🇭🇷' },
	{ id: 18, Language: 'cs', Name: 'Czech', Flag: '🇨🇿' },
	{ id: 19, Language: 'da', Name: 'Danish', Flag: '🇩🇰' },
	{ id: 20, Language: 'nl', Name: 'Dutch', Flag: '🇳🇱' },
	{ id: 21, Language: 'en', Name: 'English', Flag: '🇬🇧' },
	{ id: 22, Language: 'eo', Name: 'Esperanto', Flag: '🏳️' },
	{ id: 23, Language: 'et', Name: 'Estonian', Flag: '🇪🇪' },
	{ id: 24, Language: 'fi', Name: 'Finnish', Flag: '🇫🇮' },
	{ id: 25, Language: 'fr', Name: 'French', Flag: '🇫🇷' },
	{ id: 26, Language: 'fy', Name: 'Frisian', Flag: '🇳🇱' },
	{ id: 27, Language: 'gl', Name: 'Galician', Flag: '🇪🇸' },
	{ id: 28, Language: 'ka', Name: 'Georgian', Flag: '🇬🇪' },
	{ id: 29, Language: 'de', Name: 'German', Flag: '🇩🇪' },
	{ id: 30, Language: 'el', Name: 'Greek', Flag: '🇬🇷' },
	{ id: 31, Language: 'gu', Name: 'Gujarati', Flag: '🇮🇳' },
	{ id: 32, Language: 'ht', Name: 'Haitian Creole', Flag: '🇭🇹' },
	{ id: 33, Language: 'ha', Name: 'Hausa', Flag: '🇳🇬' },
	{ id: 34, Language: 'haw', Name: 'Hawaiian', Flag: '🇺🇸' },
	{ id: 35, Language: 'he', Name: 'Hebrew', Flag: '🇮🇱' },
	{ id: 36, Language: 'hi', Name: 'Hindi', Flag: '🇮🇳' },
	{ id: 37, Language: 'hmn', Name: 'Hmong', Flag: '🏳️' },
	{ id: 38, Language: 'hu', Name: 'Hungarian', Flag: '🇭🇺' },
	{ id: 39, Language: 'is', Name: 'Icelandic', Flag: '🇮🇸' },
	{ id: 40, Language: 'ig', Name: 'Igbo', Flag: '🇳🇬' },
	{ id: 41, Language: 'id', Name: 'Indonesian', Flag: '🇮🇩' },
	{ id: 42, Language: 'ga', Name: 'Irish', Flag: '🇮🇪' },
	{ id: 43, Language: 'it', Name: 'Italian', Flag: '🇮🇹' },
	{ id: 44, Language: 'ja', Name: 'Japanese', Flag: '🇯🇵' },
	{ id: 45, Language: 'jv', Name: 'Javanese', Flag: '🇮🇩' },
	{ id: 46, Language: 'kn', Name: 'Kannada', Flag: '🇮🇳' },
	{ id: 47, Language: 'kk', Name: 'Kazakh', Flag: '🇰🇿' },
	{ id: 48, Language: 'km', Name: 'Khmer', Flag: '🇰🇭' },
	{ id: 49, Language: 'rw', Name: 'Kinyarwanda', Flag: '🇷🇼' },
	{ id: 50, Language: 'ko', Name: 'Korean', Flag: '🇰🇷' },
	{ id: 51, Language: 'ku', Name: 'Kurdish', Flag: '🏳️' },
	{ id: 52, Language: 'ky', Name: 'Kyrgyz', Flag: '🇰🇬' },
	{ id: 53, Language: 'lo', Name: 'Lao', Flag: '🇱🇦' },
	{ id: 54, Language: 'la', Name: 'Latin', Flag: '🏳️' },
	{ id: 55, Language: 'lv', Name: 'Latvian', Flag: '🇱🇻' },
	{ id: 56, Language: 'lt', Name: 'Lithuanian', Flag: '🇱🇹' },
	{ id: 57, Language: 'lb', Name: 'Luxembourgish', Flag: '🇱🇺' },
	{ id: 58, Language: 'mk', Name: 'Macedonian', Flag: '🇲🇰' },
	{ id: 59, Language: 'mg', Name: 'Malagasy', Flag: '🇲🇬' },
	{ id: 60, Language: 'ms', Name: 'Malay', Flag: '🇲🇾' },
	{ id: 61, Language: 'ml', Name: 'Malayalam', Flag: '🇮🇳' },
	{ id: 62, Language: 'mt', Name: 'Maltese', Flag: '🇲🇹' },
	{ id: 63, Language: 'mi', Name: 'Maori', Flag: '🇳🇿' },
	{ id: 64, Language: 'mr', Name: 'Marathi', Flag: '🇮🇳' },
	{ id: 65, Language: 'mn', Name: 'Mongolian', Flag: '🇲🇳' },
	{ id: 66, Language: 'my', Name: 'Myanmar (Burmese)', Flag: '🇲🇲' },
	{ id: 67, Language: 'ne', Name: 'Nepali', Flag: '🇳🇵' },
	{ id: 68, Language: 'no', Name: 'Norwegian', Flag: '🇳🇴' },
	{ id: 69, Language: 'ny', Name: 'Nyanja (Chichewa)', Flag: '🇲🇼' },
	{ id: 70, Language: 'or', Name: 'Odia (Oriya)', Flag: '🇮🇳' },
	{ id: 71, Language: 'ps', Name: 'Pashto', Flag: '🇦🇫' },
	{ id: 72, Language: 'fa', Name: 'Persian', Flag: '🇮🇷' },
	{ id: 73, Language: 'pl', Name: 'Polish', Flag: '🇵🇱' },
	{ id: 74, Language: 'pt', Name: 'Portuguese', Flag: '🇵🇹' },
	{ id: 75, Language: 'pa', Name: 'Punjabi', Flag: '🇮🇳' },
	{ id: 76, Language: 'ro', Name: 'Romanian', Flag: '🇷🇴' },
	{ id: 77, Language: 'ru', Name: 'Russian', Flag: '🇷🇺' },
	{ id: 78, Language: 'sm', Name: 'Samoan', Flag: '🇼🇸' },
	{ id: 79, Language: 'gd', Name: 'Scots Gaelic', Flag: '🏴' },
	{ id: 80, Language: 'sr', Name: 'Serbian', Flag: '🇷🇸' },
	{ id: 81, Language: 'st', Name: 'Sesotho', Flag: '🇱🇸' },
	{ id: 82, Language: 'sn', Name: 'Shona', Flag: '🇿🇼' },
	{ id: 83, Language: 'sd', Name: 'Sindhi', Flag: '🇵🇰' },
	{ id: 84, Language: 'si', Name: 'Sinhala (Sinhalese)', Flag: '🇱🇰' },
	{ id: 85, Language: 'sk', Name: 'Slovak', Flag: '🇸🇰' },
	{ id: 86, Language: 'sl', Name: 'Slovenian', Flag: '🇸🇮' },
	{ id: 87, Language: 'so', Name: 'Somali', Flag: '🇸🇴' },
	{ id: 88, Language: 'es', Name: 'Spanish', Flag: '🇪🇸' },
	{ id: 89, Language: 'su', Name: 'Sundanese', Flag: '🇮🇩' },
	{ id: 90, Language: 'sw', Name: 'Swahili', Flag: '🇰🇪' },
	{ id: 91, Language: 'sv', Name: 'Swedish', Flag: '🇸🇪' },
	{ id: 92, Language: 'tl', Name: 'Tagalog (Filipino)', Flag: '🇵🇭' },
	{ id: 93, Language: 'tg', Name: 'Tajik', Flag: '🇹🇯' },
	{ id: 94, Language: 'ta', Name: 'Tamil', Flag: '🇮🇳' },
	{ id: 95, Language: 'tt', Name: 'Tatar', Flag: '🇷🇺' },
	{ id: 96, Language: 'te', Name: 'Telugu', Flag: '🇮🇳' },
	{ id: 97, Language: 'th', Name: 'Thai', Flag: '🇹🇭' },
	{ id: 98, Language: 'tr', Name: 'Turkish', Flag: '🇹🇷' },
	{ id: 99, Language: 'tk', Name: 'Turkmen', Flag: '🇹🇲' },
	{ id: 100, Language: 'uk', Name: 'Ukrainian', Flag: '🇺🇦' },
	{ id: 101, Language: 'ur', Name: 'Urdu', Flag: '🇵🇰' },
	{ id: 102, Language: 'ug', Name: 'Uyghur', Flag: '🇨🇳' },
	{ id: 103, Language: 'uz', Name: 'Uzbek', Flag: '🇺🇿' },
	{ id: 104, Language: 'vi', Name: 'Vietnamese', Flag: '🇻🇳' },
	{ id: 105, Language: 'cy', Name: 'Welsh', Flag: '🏴' },
	{ id: 106, Language: 'xh', Name: 'Xhosa', Flag: '🇿🇦' },
	{ id: 107, Language: 'yi', Name: 'Yiddish', Flag: '🏳️' },
	{ id: 108, Language: 'yo', Name: 'Yoruba', Flag: '🇳🇬' },
	{ id: 109, Language: 'zu', Name: 'Zulu', Flag: '🇿🇦' },
]
