export interface ILanguageData {
	id: number
	Language: string
	Name: string
}

export const LanguageData: ILanguageData[] = [
	{ id: 1, Language: 'af', Name: 'Afrikaans' },
	{ id: 2, Language: 'sq', Name: 'Albanian' },
	{ id: 3, Language: 'am', Name: 'Amharic' },
	{ id: 4, Language: 'ar', Name: 'Arabic' },
	{ id: 5, Language: 'hy', Name: 'Armenian' },
	{ id: 6, Language: 'az', Name: 'Azerbaijani' },
	{ id: 7, Language: 'eu', Name: 'Basque' },
	{ id: 8, Language: 'be', Name: 'Belarusian' },
	{ id: 9, Language: 'bn', Name: 'Bengali' },
	{ id: 10, Language: 'bs', Name: 'Bosnian' },
	{ id: 11, Language: 'bg', Name: 'Bulgarian' },
	{ id: 12, Language: 'ca', Name: 'Catalan' },
	{ id: 13, Language: 'ceb', Name: 'Cebuano' },
	{ id: 14, Language: 'zh-CN', Name: 'Chinese (Simplified)' },
	{ id: 15, Language: 'zh-TW', Name: 'Chinese (Traditional)' },
	{ id: 16, Language: 'co', Name: 'Corsican' },
	{ id: 17, Language: 'hr', Name: 'Croatian' },
	{ id: 18, Language: 'cs', Name: 'Czech' },
	{ id: 19, Language: 'da', Name: 'Danish' },
	{ id: 20, Language: 'nl', Name: 'Dutch' },
	{ id: 21, Language: 'en', Name: 'English' },
	{ id: 22, Language: 'eo', Name: 'Esperanto' },
	{ id: 23, Language: 'et', Name: 'Estonian' },
	{ id: 24, Language: 'fi', Name: 'Finnish' },
	{ id: 25, Language: 'fr', Name: 'French' },
	{ id: 26, Language: 'fy', Name: 'Frisian' },
	{ id: 27, Language: 'gl', Name: 'Galician' },
	{ id: 28, Language: 'ka', Name: 'Georgian' },
	{ id: 29, Language: 'de', Name: 'German' },
	{ id: 30, Language: 'el', Name: 'Greek' },
	{ id: 31, Language: 'gu', Name: 'Gujarati' },
	{ id: 32, Language: 'ht', Name: 'Haitian Creole' },
	{ id: 33, Language: 'ha', Name: 'Hausa' },
	{ id: 34, Language: 'haw', Name: 'Hawaiian' },
	{ id: 35, Language: 'he', Name: 'Hebrew' },
	{ id: 36, Language: 'hi', Name: 'Hindi' },
	{ id: 37, Language: 'hmn', Name: 'Hmong' },
	{ id: 38, Language: 'hu', Name: 'Hungarian' },
	{ id: 39, Language: 'is', Name: 'Icelandic' },
	{ id: 40, Language: 'ig', Name: 'Igbo' },
	{ id: 41, Language: 'id', Name: 'Indonesian' },
	{ id: 42, Language: 'ga', Name: 'Irish' },
	{ id: 43, Language: 'it', Name: 'Italian' },
	{ id: 44, Language: 'ja', Name: 'Japanese' },
	{ id: 45, Language: 'jv', Name: 'Javanese' },
	{ id: 46, Language: 'kn', Name: 'Kannada' },
	{ id: 47, Language: 'kk', Name: 'Kazakh' },
	{ id: 48, Language: 'km', Name: 'Khmer' },
	{ id: 49, Language: 'rw', Name: 'Kinyarwanda' },
	{ id: 50, Language: 'ko', Name: 'Korean' },
	{ id: 51, Language: 'ku', Name: 'Kurdish' },
	{ id: 52, Language: 'ky', Name: 'Kyrgyz' },
	{ id: 53, Language: 'lo', Name: 'Lao' },
	{ id: 54, Language: 'la', Name: 'Latin' },
	{ id: 55, Language: 'lv', Name: 'Latvian' },
	{ id: 56, Language: 'lt', Name: 'Lithuanian' },
	{ id: 57, Language: 'lb', Name: 'Luxembourgish' },
	{ id: 58, Language: 'mk', Name: 'Macedonian' },
	{ id: 59, Language: 'mg', Name: 'Malagasy' },
	{ id: 60, Language: 'ms', Name: 'Malay' },
	{ id: 61, Language: 'ml', Name: 'Malayalam' },
	{ id: 62, Language: 'mt', Name: 'Maltese' },
	{ id: 63, Language: 'mi', Name: 'Maori' },
	{ id: 64, Language: 'mr', Name: 'Marathi' },
	{ id: 65, Language: 'mn', Name: 'Mongolian' },
	{ id: 66, Language: 'my', Name: 'Myanmar (Burmese)' },
	{ id: 67, Language: 'ne', Name: 'Nepali' },
	{ id: 68, Language: 'no', Name: 'Norwegian' },
	{ id: 69, Language: 'ny', Name: 'Nyanja (Chichewa)' },
	{ id: 70, Language: 'or', Name: 'Odia (Oriya)' },
	{ id: 71, Language: 'ps', Name: 'Pashto' },
	{ id: 72, Language: 'fa', Name: 'Persian' },
	{ id: 73, Language: 'pl', Name: 'Polish' },
	{ id: 74, Language: 'pt', Name: 'Portuguese' },
	{ id: 75, Language: 'pa', Name: 'Punjabi' },
	{ id: 76, Language: 'ro', Name: 'Romanian' },
	{ id: 77, Language: 'ru', Name: 'Russian' },
	{ id: 78, Language: 'sm', Name: 'Samoan' },
	{ id: 79, Language: 'gd', Name: 'Scots Gaelic' },
	{ id: 80, Language: 'sr', Name: 'Serbian' },
	{ id: 81, Language: 'st', Name: 'Sesotho' },
	{ id: 82, Language: 'sn', Name: 'Shona' },
	{ id: 83, Language: 'sd', Name: 'Sindhi' },
	{ id: 84, Language: 'si', Name: 'Sinhala (Sinhalese)' },
	{ id: 85, Language: 'sk', Name: 'Slovak' },
	{ id: 86, Language: 'sl', Name: 'Slovenian' },
	{ id: 87, Language: 'so', Name: 'Somali' },
	{ id: 88, Language: 'es', Name: 'Spanish' },
	{ id: 89, Language: 'su', Name: 'Sundanese' },
	{ id: 90, Language: 'sw', Name: 'Swahili' },
	{ id: 91, Language: 'sv', Name: 'Swedish' },
	{ id: 92, Language: 'tl', Name: 'Tagalog (Filipino)' },
	{ id: 93, Language: 'tg', Name: 'Tajik' },
	{ id: 94, Language: 'ta', Name: 'Tamil' },
	{ id: 95, Language: 'tt', Name: 'Tatar' },
	{ id: 96, Language: 'te', Name: 'Telugu' },
	{ id: 97, Language: 'th', Name: 'Thai' },
	{ id: 98, Language: 'tr', Name: 'Turkish' },
	{ id: 99, Language: 'tk', Name: 'Turkmen' },
	{ id: 100, Language: 'uk', Name: 'Ukrainian' },
	{ id: 101, Language: 'ur', Name: 'Urdu' },
	{ id: 102, Language: 'ug', Name: 'Uyghur' },
	{ id: 103, Language: 'uz', Name: 'Uzbek' },
	{ id: 104, Language: 'vi', Name: 'Vietnamese' },
	{ id: 105, Language: 'cy', Name: 'Welsh' },
	{ id: 106, Language: 'xh', Name: 'Xhosa' },
	{ id: 107, Language: 'yi', Name: 'Yiddish' },
	{ id: 108, Language: 'yo', Name: 'Yoruba' },
	{ id: 109, Language: 'zu', Name: 'Zulu' },
]
